server:
  port: 10020
#---------------------------------------------------------------------
spring:
  profiles:
    active: native
  application:
    name: config-server
#  cloud:
#    consul:
#      host: 192.168.1.80
#      port: 8500
#      discovery:
#        enabled: true
#        register: true
#        healthCheckInterval: 5s
#        health-check-timeout: 1s
#        prefer-ip-address: true
#        health-check-path: /actuator/health
#---------------------------------------------------------------------
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    status-page-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
    hostname: localhost
  client:
    register-with-eureka: true #是否注册到注册中心
    fetch-registry: true #是否从注册中心拉取注册服务列表
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:10010/eureka/
#---------------------------------------------------------------------
#监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#---------------------------------------------------------------------
info:
  version: 1.0.0
  app:
    name: ${spring.application.name}
#---------------------------------------------------------------------