spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        #配置管理端的微服务
        - id: manage-server
          uri: lb://manage-server
          predicates:
            - Path=/manage/**
          filters:
            - StripPrefix=1
        #配置跳转监控的微服务
        - id: monitor-server
          uri: lb://monitor-server
          predicates:
            - Path=/monitor/**
          filters:
            - StripPrefix=1